// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdminController from "./admin_controller"
application.register("admin", AdminController)

import AppController from "./app_controller"
application.register("app", AppController)

import HljsController from "./hljs_controller"
application.register("hljs", HljsController)

import RecaptchaController from "./recaptcha_controller"
application.register("recaptcha", RecaptchaController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SiteProductController from "./site_product_controller"
application.register("site-product", SiteProductController)

import SlugController from "./slug_controller"
application.register("slug", SlugController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import UserClaimsController from "./user_claims_controller"
application.register("user-claims", UserClaimsController)

import UserPoliciesController from "./user_policies_controller"
application.register("user-policies", UserPoliciesController)
